
spring:
  application.name: test-data
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true #데이터 초기화 시점이 jpa가 데이터소스를 초기화한 이후로 변경
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always  #초가화 데이터 삽입
  security.oauth2.client:
    registration:
      github:
        client-id: ${GITHUB_CLIENT_ID}
        client-secret: ${GITHUB_CLIENT_SECRET}


debug: false
logging:
  level:
    charles.sample.testdata: debug
    org.springframework.web.servlet: debug
    #org.hibernate.SQL: debug #실행되는 SQL 출력
    org.hibernate.orm.jdbc.bind: trace #바인딩 파라미터 값 출력
    org.springframework.test.context.transaction.TransactionContext: debug
---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
  username:
  password: