
spring:
  application.name: test-data
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
  jpa:
    open-in-view: false
    defer-datasource-initialization: true #데이터 초기화 시점이 jpa가 데이터소스를 초기화한 이후로 변경
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always  #초가화 데이터 삽입

debug: false
logging:
  level:
    charles.sample.testdata: debug
    org.springframework.web.servlet: debug


---

#spring:
#  config.activate.on-profile: test
#  datasource.url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;